name: Flutter Analyze
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  FLUTTER_VERSION: "3.35.4"
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
      - name: Dependencies
        run: flutter pub get
        working-directory: app
      - name: Check format
        run: dart format --line-length 150 --set-exit-if-changed lib test
        working-directory: app
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
      - name: Dependencies
        run: flutter pub get
        working-directory: app
      - name: Analyze
        run: flutter analyze
        working-directory: app
